# Generated by Django 3.2.4 on 2021-07-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
                ('Precio', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Imagen', models.ImageField(upload_to='static/img/productos/')),
                ('Componente', models.ForeignKey(blank='', null='', on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('Fabricante', models.ForeignKey(blank='', null='', on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
            ],
        ),
    ]
